version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  postgres:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb  
  blazegraph:
    image: nawer/blazegraph:latest
    ports:
      - "9999:9999"
  sepa:
    image: arces/sepa:0.10.0-SNAPSHOT-1
    volumes:
      - ./endpoint.jpar:/usr/sepa/endpoint.jpar
    ports:
      - "8000:8000"
      - "8443:8443"
      - "9000:9000"
      - "9443:9443"
    depends_on:
      - blazegraph
  scorpio:
    image: vaimee/scorpio:1.0.6
    ports:
      - "9090:9090" 
    depends_on:
      - kafka
      - postgres
      - sepa
    environment:
      QUERY_LANGUAGE: SPARQL
      SEPA_HOST: sepa
      SEPA_PORT: 8000 
      SEPA_SCHEME: http
      SEPA_PATH_QUERY: /sparql
      SEPA_PATH_UPDATE: /sparql
      
